config/routes.rb
Rails.application.routes.draw do

  root 'tweets#index'

  resources :tweets

end

app/models/tweet.rb
require 'elasticsearch/persistence/model'

class Tweet
  include Elasticsearch::Persistence::Model


  # settings index: { number_of_shards: 1 } do
  #   mappings dynamic: 'false' do
  #     indexes :text, type: 'string'
  #   end
  # end


  # mappings do
  #   indexes :text, type: 'string'
  #   indexes :coordinates do
  #     indexes :coordinates, type: 'geo_point'
  #     indexes :type, type: 'string'
  #   end
  # end


  attribute :text, String
  attribute :coordinates, Hash , mapping: {type: 'object', properties: {coordinates: {type: 'geo_point',  geohash: true,
                                          geohash_prefix: true,  geohash_precision: 10}, type: {type: 'string'}}}
  attribute :entities, Hash, mapping: {type: 'object'}

  validates :text, presence: true


  def self.nearby(lat, lng, distance, unit = 'mi', hashtags = [])
    query = {
        :size => 250,
        :query => {
            :filtered => {
                :filter => {
                    :geohash_cell => {
                        :coordinates => {
                            :lat =>  lat,
                            :lon => lng
                        },
                        :neighbors =>  true,
                        :precision => distance.to_s+unit
                    }
                }, :_cache => true
            },
        },
        :sort => { :created_at => { :order => 'desc' }}
    }

    unless hashtags.empty?
      query[:query][:filtered][:query] = {
          :bool => {
              :must => [
                  {
                      :query_string => {
                          :default_field => 'tweet.entities.hashtags.text',
                          :query => hashtags.join(' ')
                      }
                  }
              ]
          }
      }
    end

    response = Hashie::Mash.new (Tweet.search query).response
    response.hits.hits.each do |tweet|
      p tweet._source.text   + "  " + tweet._source.created_at
    end
    response
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    unless params[:search].nil? or params[:search][:latitude].nil? or params[:search][:longitude].nil? or params[:search][:radius].nil?
      htags = []

      htags = params[:search][:hashtags].split(',') unless params[:search][:hashtags].nil?
      nearby = Tweet.nearby params[:search][:latitude].to_f, params[:search][:longitude].to_f,  params[:search][:longitude].to_i, 'km', htags
      @tweets = []

      picture =  {
          :url => 'http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|00D900',
          :width =>  36,
          :height => 36
      }

      @hash = Gmaps4rails.build_markers(nearby.hits.hits) do |tweet, marker|
        marker.lat tweet._source.coordinates.coordinates[1]
        marker.lng tweet._source.coordinates.coordinates[0]
        marker.picture picture
        marker.infowindow tweet._source.text
        hash = {:tweet => tweet._source.text, :time => Time.parse(tweet._source.created_at).in_time_zone('Pacific Time (US & Canada)')}
        @tweets.append hash
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twstream</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Tweet Streamer</a>
  </div>
</nav>

<%= yield %>

</body>
</html>

app/views/tweets/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<%= simple_form_for :search,  url: tweets_path , :method => :get, :remote => false, :validate=>true,  :html => {  :class => 'form form-vertical validate-form', :style => 'margin-bottom: 0;'} do |f| %>
    <div class="row">
      <div class="clearfix">
        <div class='col-sm-3'>
          <div class='box'>
            <div class='lead'>
              <i class='icon-map-marker contrast'></i>
              Latitude
            </div>
            <% unless params[:search].nil? or  params[:search][:latitude].nil?%>
                <%= f.input :latitude,  placeholder: 'Latitude', input_html: {value: params[:search][:latitude], class: 'form-control', :'data-rule-required' => true, required: true}, label: false, as: :float %>
            <%else %>
                <%= f.input :latitude,  placeholder: 'Latitude', input_html: {class: 'form-control', :'data-rule-required' => true, required: true}, label: false, as: :float %>
            <% end %>
          </div>
        </div>
        <div class='col-sm-3'>
          <div class='box'>
            <div class='lead'>
              <i class='icon-map-marker contrast'></i>
              Longitude
            </div>
            <% unless params[:search].nil? or  params[:search][:longitude].nil?%>
                <%= f.input :longitude, placeholder: 'Longitude', input_html: { value: params[:search][:longitude],class: 'form-control', :'data-rule-required' => true}, label: false, as: :float %>
            <%else %>
                <%= f.input :longitude, placeholder: 'Longitude', input_html: {class: 'form-control', :'data-rule-required' => true}, label: false, as: :float %>
            <% end %>

          </div>
        </div>
        <div class='col-sm-3'>
          <div class='box'>
            <div class='lead'>
              <i class='icon-map-marker contrast'></i>
              Radius (in km)
            </div>
            <% unless params[:search].nil? or  params[:search][:radius].nil?%>
                <%= f.input :radius,  placeholder: 'Radius in KMs', input_html: { value: params[:search][:radius], class: 'form-control',min:1, step: 1, type: 'number', :'data-rule-required' => true}, label: false%>
            <%else %>
                <%= f.input :radius,  placeholder: 'Radius in KMs', input_html: {class: 'form-control',min:1, step: 1, type: 'number', :'data-rule-required' => true}, label: false%>
            <% end %>

          </div>
        </div>
      </div>
      <div class="clearfix">
        <div class='col-sm-7'>
          <div class='box'>
            <div class='lead'>
              <i class='icon-map-marker contrast'></i>
              Hashtags
            </div>
            <% unless params[:search].nil? or  params[:search][:hashtags].nil?%>
                <%= f.input :hashtags,  placeholder: 'Hashtags (comma delimited)', input_html: { value: params[:search][:hashtags], class: 'form-control'}, label: false,  as: :text %>
            <%else %>
                <%= f.input :hashtags,  placeholder: 'Hashtags (comma delimited)', input_html: {class: 'form-control'}, label: false,  as: :text %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
    <%= f.submit 'Search', input_html: {value: 'no_maps', class: 'btn btn-danger btn-block btn-lg'}%>
<% end %>


<% unless @tweets.nil? or @tweets.empty? %>
    <br><br>
    <b><p>Tweets from matching the search criteria</p></b>
    <table class="table table-hover table-bordered">
    <tr><th>Tweet</th>
    <th>Created At</th></tr>
    <% @tweets.each do |tweet|%>
     <tr><td><%= tweet[:tweet] %></td>
      <td><%= tweet[:time] %></td></tr>
    <% end %>
    </table>

    <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
    </div>

    <script type="application/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();

        });
    </script>
<% end %>

app/views/welcome/index.html.erb
<%= simple_form_for :search,  url: tweets_path , :method => :get, :remote => true, :validate=>true,  :html => {  :class => 'form form-vertical validate-form', :style => 'margin-bottom: 0;'} do |f| %>
              <div class="row">
                  <div class="clearfix">
                    <div class='col-sm-3'>
                      <div class='box'>
                        <div class='lead'>
                          <i class='icon-map-marker contrast'></i>
                          Latitude
                        </div>
                        <%= f.input :latitude,  placeholder: 'Latitude', input_html: { class: 'form-control', :'data-rule-required' => true, required: true}, label: false, as: :float %>
                      </div>
                    </div>
                  <div class='col-sm-3'>
                    <div class='box'>
                      <div class='lead'>
                        <i class='icon-map-marker contrast'></i>
                        Longitude
                      </div>
                      <%= f.input :longitude,  placeholder: 'Longitude', input_html: { class: 'form-control', :'data-rule-required' => true}, label: false, as: :float %>
                    </div>
                  </div>
                    <div class='col-sm-3'>
                      <div class='box'>
                        <div class='lead'>
                          <i class='icon-map-marker contrast'></i>
                          Radius
                        </div>
                        <%= f.input :radius,  placeholder: 'Radius in Miles', input_html: { class: 'form-control', :'data-rule-required' => true}, label: false,  as: :float%>
                      </div>
                    </div>
                </div>
                <div class="clearfix">
                  <div class='col-sm-7'>
                    <div class='box'>
                      <div class='lead'>
                        <i class='icon-map-marker contrast'></i>
                        Hashtags
                      </div>
                      <%= f.input :hashtags,  placeholder: 'Hashtags (comma delimited)', input_html: { class: 'form-control'}, label: false,  as: :text %>
                    </div>
                  </div>
                </div>
              </div>
    <%= f.submit 'Search', input_html: {class: 'btn btn-danger btn-block btn-lg'}%>
<% end %>


<% if @tweets %>
    <tbody>
    <% @tweets.each do |lkup| %>
        <tr >
          <td><input type="text" class="lkupcode" value=<%= lkup %> /></td>
        </tr>
    <% end %>
    </tbody>
<% end %>